//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.Blazor;

[assembly: RegisterDocumentType(CarouselItem.CLASS_NAME, typeof(CarouselItem))]

namespace CMS.DocumentEngine.Types.Blazor
{
	/// <summary>
	/// Represents a content item of type CarouselItem.
	/// </summary>
	public partial class CarouselItem : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "Blazor.CarouselItem";


		/// <summary>
		/// The instance of the class that provides extended API for working with CarouselItem fields.
		/// </summary>
		private readonly CarouselItemFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// CarouselItemID.
		/// </summary>
		[DatabaseIDField]
		public int CarouselItemID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("CarouselItemID"), 0);
			}
			set
			{
				SetValue("CarouselItemID", value);
			}
		}


		/// <summary>
		/// Title.
		/// </summary>
		[DatabaseField]
		public string Title
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Title"), @"");
			}
			set
			{
				SetValue("Title", value);
			}
		}


		/// <summary>
		/// Text.
		/// </summary>
		[DatabaseField]
		public string Text
		{
			get
			{
				return ValidationHelper.GetString(GetValue("Text"), @"");
			}
			set
			{
				SetValue("Text", value);
			}
		}


		/// <summary>
		/// BackgroundImage.
		/// </summary>
		[DatabaseField]
		public string BackgroundImage
		{
			get
			{
				return ValidationHelper.GetString(GetValue("BackgroundImage"), "");
			}
			set
			{
				SetValue("BackgroundImage", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with CarouselItem fields.
		/// </summary>
		[RegisterProperty]
		public CarouselItemFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with CarouselItem fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class CarouselItemFields : AbstractHierarchicalObject<CarouselItemFields>
		{
			/// <summary>
			/// The content item of type CarouselItem that is a target of the extended API.
			/// </summary>
			private readonly CarouselItem mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="CarouselItemFields" /> class with the specified content item of type CarouselItem.
			/// </summary>
			/// <param name="instance">The content item of type CarouselItem that is a target of the extended API.</param>
			public CarouselItemFields(CarouselItem instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// CarouselItemID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.CarouselItemID;
				}
				set
				{
					mInstance.CarouselItemID = value;
				}
			}


			/// <summary>
			/// Title.
			/// </summary>
			public string Title
			{
				get
				{
					return mInstance.Title;
				}
				set
				{
					mInstance.Title = value;
				}
			}


			/// <summary>
			/// Text.
			/// </summary>
			public string Text
			{
				get
				{
					return mInstance.Text;
				}
				set
				{
					mInstance.Text = value;
				}
			}


			/// <summary>
			/// Page target.
			/// </summary>
			public IEnumerable<TreeNode> PageTarget
			{
				get
				{
					return mInstance.GetRelatedDocuments("PageTarget");
				}
			}


			/// <summary>
			/// BackgroundImage.
			/// </summary>
			public IEnumerable<DocumentAttachment> BackgroundImage
			{
				get
				{
					return mInstance.GetFieldDocumentAttachments("BackgroundImage");
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="CarouselItem" /> class.
		/// </summary>
		public CarouselItem() : base(CLASS_NAME)
		{
			mFields = new CarouselItemFields(this);
		}

		#endregion
	}
}